# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

def generate_fibonacci(up_to_number)
  fibonacci_numbers = [1, 2]
  while fibonacci_numbers[-2] + fibonacci_numbers[-1] <= up_to_number
    fibonacci_numbers << fibonacci_numbers[-2] + fibonacci_numbers[-1]
 end
  fibonacci_numbers
end

p generate_fibonacci(4_000_000).select{ |num| num.even? }.reduce(:+)